on: [push]

jobs:
  build_spec:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 🐍 install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Cache poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install python dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        $HOME/.local/bin/poetry install

    - name: Generate spec
      run: |
        poetry run ./main.py

    - name: Upload spec
      env:
        RTOF_UPLOAD_URL: ${{ secrets.SHAREPOINT_UPLOAD_WEBHOOK }}
      run: |
        poetry run bin/upload.py output/specification.docx "$RTOF_UPLOAD_URL"
        poetry run bin/upload.py output/specification-records.xlsx "$RTOF_UPLOAD_URL"
        poetry run bin/upload.py output/specification-dimensions.xlsx "$RTOF_UPLOAD_URL"
        poetry run bin/upload.py output/record-relationships.png "$RTOF_UPLOAD_URL"

